services:
  ports:
    gateway: 1000
    jwt: 2000
    auth: 3000
    project: 4000
    projectrule: 5000
    projectleader: 6000
  urls:
    gateway: localhost
    jwt: localhost
    auth: localhost
    project: localhost
    projectrule: localhost
    projectleader: localhost
    
    
spring:
  r2dbc:
    username: postgres
    password: root
    url: r2dbc:postgresql://localhost:5432/progem
