services:
  ports:
    gateway: 1000
    auth: 2000
    project: 3000
    projectrule: 4000
    projectleader: 5000
  urls:
    gateway: localhost
    jwt: localhost
    auth: localhost
    project: localhost
    projectrule: localhost
    projectleader: localhost
    
    
spring:
  r2dbc:
    username: postgres
    password: root
    url: r2dbc:postgresql://localhost:5432/progem


table:
  users:
    name: users
    email: email
    password: cred
